# What is ci.yml?
#
# Think of ci.yml as an instruction sheet for GitHub.
#
# When GitHub sees:
#
# .github/workflows/ci.yml
#
# it knows:
#
# "This is a GitHub Actions workflow.
# I need to read this file and execute the instructions inside it."
#
#
# Our basic CI flow will be:
#
# Developer
#     ↓
# git push
#     ↓
# GitHub
#     ↓
# GitHub Actions
#     ↓
# Run our CI tasks
#     ↓
# Success or Failure

#This is simply the name of the workflow you'll see in GitHub Actions.
name: CI Pipeline

#This tells GitHub when to run the workflow.
#In plain English:
#"Run this workflow whenever someone pushes code to main."
on:
  push:
    branches:
      - main
#This defines a job called test.
jobs:
  test:
    #This tells GitHub:
    #"Run this job on an Ubuntu machine."
    runs-on: ubuntu-latest
    #This tells GitHub Actions: Take the code from my GitHub repository and check it out onto the Ubuntu runner.
    steps:
      - name: Checkout code
        #Use Means, Use an already-created GitHub Action instead of writing all the commands myself.
        uses: actions/checkout@v4

        # Set up the PHP version required by our project
      # instead of relying on the runner's default PHP version.
      # So even if GitHub's default PHP version changes in the future, your workflow still requests PHP 8.2.
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

        ## Check which PHP version is currently available
        # on the GitHub Actions Ubuntu runner.
      - name: Check PHP version
        run:
          php --version

          # Check PHP files for syntax errors.
      # The | allows us to run multiple commands
      # inside the same run block.

      # - name: Check PHP syntax
      #   run: |
      #     # Check the syntax of config.php without executing it.
      #     php -l php/config.php

      #     # Check the syntax of tasks.php without executing it.
      #     php -l php/tasks.php

      # Find every PHP file in the project
      # and check each one for syntax errors.
      - name: Check PHP syntax
        run: |
        find . -type f -name "*.php" -exec php -l {} \;

      - name: List project files
        #What does ls -la mean?
        #Show me the files and folders in the current directory.
        #Run Means, Run this Linux/shell command on the GitHub Actions machine.
        run: ls -la
